-- Deferred SQL — apply on the Windows side once politics.db is openable.
-- Cowork agent run 2026-05-04: bash sandbox unavailable (No space left on device); DB not opened.

INSERT INTO weekly_themes (window_start, window_end, themes, open_questions, underserved_topics, summary, avoid_list, note_count, generated_at)
VALUES (
  '2026-04-28',
  '2026-05-04',
  '["fiscal discipline vs. spending growth | Listener has flagged property tax as too high (4/27) and supports non-essential spending cuts (4/28); the four MoCo Exec front-runners differ on FY26 budget growth and the affordability cap.","candidate full-history dossiers | Listener wants pre-recent-session record (4/26) and historical viewpoint over time (4/25); they have explicitly told us prior episodes promised this and did not deliver.","concrete policy comparison across the listener''s actual ballot races | Listener wants side-by-side, not survey of the field (4/24, 4/26, 4/28).","MCPS structural decisions affecting them as a Rockville parent | New grading system (4/30) and the Wootton relocation (4/29) are both Board of Education decisions, not Council decisions, and prior episodes have conflated the two institutions.","sanctuary policy as a litmus test | Listener has asked the same question three weeks in a row (4/24): which Democratic primary candidates actually oppose sanctuary policy on illegal immigration. The honest answer for MoCo Democrats is none, and we should say so plainly without burying it."]',
  '["Is Andrew Friedson the candidate who stands for fiscal restriction and spending discipline?","Why does MCPS want to close and move Wootton High School, and what happens next?","What is Kramer''s full historical voting record, including old news beyond recent sessions?","What are the documented policy differences between each candidate on my primary ballot?","Which Democratic primary candidate actually opposes sanctuary policy on illegal immigration?","What is the new MCPS rating system actually doing — what changes for my kid?"]',
  '["Council At-Large field — listener votes for At-Large but no At-Large candidate has been profiled yet; tier 1 priority","MoCo Board of Education race — the Wootton and grading-system questions actually live here, but no BoE candidate has been profiled","MoCo State''s Attorney, Sheriff, Clerk, Register, Orphans'' Court — listener has voting rights and zero coverage","U.S. Representative MD-8 — Raskin race has five filed Democrats but no episode yet","Property-tax-rate trajectory and the spending affordability guidelines vote — listener''s stated priority but not directly explained","How a registered Democrat actually casts a vote against sanctuary policy in 2026 MoCo — i.e., the answer is the November ballot, not the June primary"]',
  'Listener is a registered Democrat in Rockville (Council D7, MD-19) heading into the June 23 primary. Dominant request is sustained, candidate-by-candidate, full-history coverage rather than recent-vote roll-call summaries. Specific named asks they keep restating: Andrew Friedson and fiscal restriction; Wootton High School relocation; Ben Kramer''s full historical voting record; the new MCPS school rating system; which Democratic primary candidates actually oppose sanctuary policy. They are now committed (4/28) to focusing on the primary and have signaled support for non-essential spending cuts and against high property tax.',
  '["The framing ''a listener asked us last week/earlier this week which Democratic primary candidates actually oppose sanctuary policy on illegal immigration'' — used in 4/28 ep1 and 4/29 ep3","The Evan Glass DHS-screening bill as the sanctuary-policy hook — 4/28 ep1 and 4/29 ep3","The ICE agent mask-ban ordinance as the sanctuary-policy benchmark — 4/29 ep2","''Two stories, properly worked through'' / ''two stories, not spreading thin across six'' as an episode-framing device — 4/29 ep1","Governor Moore''s ''Leave No One Behind'' slogan contrasted with disability services cuts — 4/27 ep1 and ep1.rewrite","The ACA marketplace quiet-downgrade story — 4/28 ep1 and 4/29 ep3","Maryland''s 90-day part-time legislature explainer — 4/26 ep3 and ep3.rewrite","The wave of 25 Maryland lawmakers retiring or running for other offices — 4/26 ep1, ep1.rewrite, ep4","The Beltsville Agricultural Research Center closure as a District 19 candidate-record hook — 4/27 ep4 and ep4.rewrite","Listener''s own frustration about promised candidate deep-dives not delivering — already narrated back across at least five episodes","The Friedson cash-on-hand $2.1M cycle-to-date number — 5/3 ep3","The labor-endorsement landscape paragraph — 5/3 ep3","The Sage at Shady Grove + More Housing N.O.W. illustration — 5/3 ep3"]',
  7,
  '2026-05-04T20:00:00-04:00'
)
ON CONFLICT(window_start, window_end) DO UPDATE SET
  themes=excluded.themes,
  open_questions=excluded.open_questions,
  underserved_topics=excluded.underserved_topics,
  summary=excluded.summary,
  avoid_list=excluded.avoid_list,
  note_count=excluded.note_count,
  generated_at=excluded.generated_at;
